# Generated by Django 5.2.3 on 2025-06-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sacramento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bautizo", "Bautizo"),
                            ("comunion", "Primera Comunión"),
                            ("confirmacion", "Confirmación"),
                            ("matrimonio", "Matrimonio"),
                            ("defuncion", "Defunción"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Sacramento",
                "verbose_name_plural": "Sacramentos",
            },
        ),
    ]
