# Generated by Django 5.2.3 on 2025-06-26 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bautismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrante', models.CharField(max_length=100)),
                ('iglesia', models.CharField(max_length=100)),
                ('padrinos', models.TextField()),
                ('sacramento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_bautismo', to='sacramentos.sacramento')),
            ],
            options={
                'verbose_name': 'Bautismo',
                'verbose_name_plural': 'Bautismos',
            },
        ),
    ]
