# Generated by Django 5.2.3 on 2025-06-27 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0003_bautizo_delete_bautismo_delete_sacramento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bautizo',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='bautizo',
            name='apellidos_bautizado',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bautizo',
            name='nombres_bautizado',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
