# Generated by Django 5.2.3 on 2025-06-27 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0004_remove_bautizo_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bautizo',
            name='nombre_madre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bautizo',
            name='nombre_padre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
