# Generated by Django 5.2.3 on 2025-06-27 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0005_bautizo_nombre_madre_bautizo_nombre_padre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bautizo',
            name='padrinos',
        ),
        migrations.AddField(
            model_name='bautizo',
            name='nombre_madrina',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bautizo',
            name='nombre_padrino',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
