# Generated by Django 5.2.3 on 2025-06-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0006_remove_bautizo_padrinos_bautizo_nombre_madrina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_novio', models.CharField(max_length=100)),
                ('apellidos_novio', models.CharField(max_length=100)),
                ('nombres_novia', models.CharField(max_length=100)),
                ('apellidos_novia', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('celebrante', models.CharField(max_length=100)),
                ('iglesia', models.CharField(max_length=100)),
                ('nombre_padrino_novio', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_madrina_novio', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_padrino_novia', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_madrina_novia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
